# Generated by Django 4.1.3 on 2022-11-26 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, null=True)),
                ('img', models.ImageField(upload_to='details/')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='image', to='offer_start.image')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='offer_start.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(blank=True, max_length=12)),
                ('call_number', models.CharField(blank=True, max_length=60)),
                ('avatar', models.ImageField(null=True, upload_to='img/')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('surname', models.CharField(blank=True, max_length=60)),
                ('birth_date', models.DateField(blank=True)),
                ('locate', models.CharField(blank=True, max_length=255)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('sub_industry', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=60)),
                ('gender', models.CharField(blank=True, max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(null=True, upload_to='img/')),
                ('inn', models.CharField(blank=True, max_length=12)),
                ('call_number', models.CharField(blank=True, max_length=60)),
                ('name', models.CharField(blank=True, max_length=60)),
                ('create_date', models.DateField(blank=True)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('locate', models.CharField(blank=True, max_length=255)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=60)),
                ('about', models.CharField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bussinessmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(null=True, upload_to='img/')),
                ('inn', models.CharField(blank=True, max_length=12)),
                ('call_number', models.CharField(blank=True, max_length=60)),
                ('name', models.CharField(blank=True, max_length=60)),
                ('surname', models.CharField(blank=True, max_length=60)),
                ('birth_date', models.DateField(blank=True)),
                ('locate', models.CharField(blank=True, max_length=255)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('sub_industry', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=60)),
                ('gender', models.CharField(blank=True, max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bussinessmen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
