# Generated by Django 4.1.3 on 2022-11-20 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12)),
                ('call_number', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('birth_date', models.DateField()),
                ('locate', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('sub_industry', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=60)),
                ('gender', models.CharField(max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12)),
                ('call_number', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('create_date', models.DateField()),
                ('url', models.CharField(max_length=255)),
                ('locate', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=60)),
                ('about', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bussinessmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12)),
                ('call_number', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('birth_date', models.DateField()),
                ('locate', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('sub_industry', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=60)),
                ('gender', models.CharField(max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bussinessmen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
