# Generated by Django 4.1.3 on 2022-11-28 07:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offer_start', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bussinessmen',
            new_name='Businessman',
        ),
        migrations.AlterModelOptions(
            name='businessman',
            options={'verbose_name': 'Предприниматель', 'verbose_name_plural': 'Предприниматели'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображения', 'verbose_name_plural': 'Изображение'},
        ),
        migrations.AlterModelOptions(
            name='investor',
            options={'verbose_name': 'Инвестор', 'verbose_name_plural': 'Инвесторы'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name': 'Тип услуги', 'verbose_name_plural': 'Типы услуг'},
        ),
    ]
