# Generated by Django 4.1.3 on 2022-11-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_start', '0002_rename_bussinessmen_businessman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessman',
            name='role',
            field=models.CharField(default='bus', editable=False, max_length=12),
        ),
        migrations.AddField(
            model_name='company',
            name='role',
            field=models.CharField(default='com', editable=False, max_length=12),
        ),
        migrations.AddField(
            model_name='investor',
            name='role',
            field=models.CharField(default='inv', editable=False, max_length=12),
        ),
    ]
