# Generated by Django 4.1.3 on 2022-11-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_start', '0003_alter_bussinessmen_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussinessmen',
            name='avatar',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='company',
            name='avatar',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='investor',
            name='avatar',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
