# Generated by Django 4.1.3 on 2022-11-25 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer_start', '0004_bussinessmen_avatar_company_avatar_investor_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, null=True)),
                ('img', models.ImageField(upload_to='details/')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='image', to='offer_start.image')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='offer_start.servicetype')),
            ],
        ),
    ]
