# Generated by Django 4.1.3 on 2022-11-11 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expenditure',
            new_name='MoneyOperation',
        ),
    ]
