# Generated by Django 4.1.3 on 2022-11-11 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econo', '0002_rename_expenditure_moneyoperation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('sum', models.FloatField(max_length=255, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10000000000.0)])),
                ('date', models.DateField()),
                ('operation', models.CharField(default='Расходы', editable=False, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('sum', models.FloatField(max_length=255, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10000000000.0)])),
                ('date', models.DateField()),
                ('operation', models.CharField(default='Доходы', editable=False, max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='MoneyOperation',
        ),
    ]
