# Generated by Django 4.1.3 on 2022-11-17 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econo', '0003_expense_income_delete_moneyoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='sum',
            field=models.FloatField(max_length=255, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10000000000.0, message='dsagdf')]),
        ),
    ]
