# Generated by Django 4.1.3 on 2022-11-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img/')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('industry', models.CharField(max_length=40)),
                ('locate', models.CharField(max_length=40, null=True)),
                ('status', models.CharField(max_length=80)),
                ('role', models.CharField(choices=[('inv', 'Инвестор'), ('bus', 'Предприниматель'), ('com', 'Компания')], max_length=30)),
            ],
        ),
    ]
