# Generated by Django 4.1.3 on 2022-11-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('inv', 'investor'), ('bus', 'businessman'), ('com', 'company')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
