# Generated by Django 4.1.3 on 2022-11-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[(1, 'Инвестор'), (2, 'Предприниматель'), (3, 'Компания')], max_length=30),
        ),
    ]
