# Generated by Django 4.1.3 on 2022-11-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='locate',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('inv', 'Инвестор'), ('bus', 'Предприниматель'), ('com', 'Компания')], max_length=30),
        ),
    ]
