# Generated by Django 4.1.3 on 2022-11-09 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_locate_alter_profile_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['industry', 'locate', 'status', 'role']},
        ),
    ]
