# Generated by Django 4.1.3 on 2022-11-23 15:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('count', models.PositiveIntegerField()),
                ('price', models.FloatField(max_length=255, validators=[django.core.validators.MaxValueValidator(50000.0, message='Цена не должна превышать 50000р'), django.core.validators.MinValueValidator(0.1, message='Цена не должна быть меньше 0р')])),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
